services:
  - type: web
    name: campusconnect
    env: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "0.0.0.0"
      - key: DJANGO_USE_WHITENOISE
        value: "True"
      - key: DB_ENGINE
        value: "sqlite3"
