# Generated by Django 6.0.7 on 2026-07-18 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_admin_approved_user_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='approval_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
