# Generated by Django 6.0.7 on 2026-07-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_approval_notes_event_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
